<?php 
/**
 * http://bigemployee.com/zend-framework-2-pagination-sorting-tutorial/
 * https://github.com/tahmina8765/zf2_search_with_pagination_example
 */ 
?>
<?php if ($this->pageCount): ?>
    <div class="text-center">
        <ul class="pagination">
            <!-- First page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->first)); ?>"><?php echo $this->translate("First"); ?></a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#"><?php echo $this->translate("First"); ?></a>
                </li>
            <?php endif; ?>
            
            
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>&role=<?=$this->role?>">
                        <?php echo $this->translate("Previous"); ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <?php echo $this->translate("Previous"); ?>
                    </a>
                </li>
            <?php endif; ?>
                
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>&role=<?=$this->role?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>&role=<?=$this->role?>">
                        <?php echo $this->translate("Next"); ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <?php echo $this->translate("Next"); ?>
                    </a>
                </li>
            <?php endif; ?>
                
            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->last; ?>&role=<?=$this->role?>"><?php echo $this->translate("Last"); ?></a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#"><?php echo $this->translate("Last"); ?></a>
                </li>
            <?php endif; ?>
                
        </ul>
    </div>
<?php endif; ?> 
