<h1>Registration/Signup</h1>
<?php #echo $this->absoluteUrl(); ?>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form-group">
	<?php echo $this->formLabel($form->get('username')); ?>
	<div class="col-sm-10"><?php echo $this->formInput($form->get('username')); ?></div>
	<p class="test-danger"><?php echo $this->formElementErrors($form->get('username'));?></p>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('country')); ?>
	<div class="col-sm-6">
		<?php echo $this->formSelect($form->get('country')); ?>
		<?php echo $this->formElementErrors($form->get('country')); ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('language')); ?>
	<div class="col-sm-6">
		<?php echo $this->formSelect($form->get('language')); ?>
		<?php echo $this->formElementErrors($form->get('language')); ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('email')); ?>
	<div class="col-sm-10">
		<?php echo $this->formInput($form->get('email')); ?>
		<?php echo $this->formElementErrors($form->get('email')); ?>
	</div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('password')); ?>
	<div class="col-sm-10"><?php echo $this->formInput($form->get('password')); ?></div>
</div>

<div class="form-group">
	<?php echo $this->formLabel($form->get('password2')); ?>
	<div class="col-sm-10">
		<?php echo $this->formInput($form->get('password2')); ?>
		<?php echo $this->formElementErrors($form->get('password2')); ?>
	</div>
</div>

<div class="form-group">
	<div class="col-md-10 col-md-offset-2"><?php echo $this->formRow($form->get('submit')); ?></div>
</div>

<?php echo $this->form()->closeTag();?>

