<div class="row login-container animated fadeInUp" style="margin-top:20px; margin-bottom:60px;">
    <div class="col-md-8 col-md-offset-2 tiles white no-padding" style="border:1px solid #E0E0E0;">
        <div class="p-t-30 p-l-40 p-b-20 xs-p-t-10 xs-p-l-10 xs-p-b-10"> 
              <h2 class="normal">Sign in</h2>
              <p>Use Facebook, Twitter or your email to sign in.<br></p>
              <p class="p-b-20">Sign up Now! for webarch accounts, it's free and always will be..</p>
        </div>
        <div class="tiles grey p-t-20 p-b-20 text-black">

			<?php
			$form = $this->form;
			$form->prepare();
			echo $this->form()->openTag($form);
			?>
			<div class="row form-row m-l-20 m-r-20 xs-m-l-10 xs-m-r-10">
				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('username')); ?></div>
					<div class="col-sm-10"><?php echo $this->formInput($form->get('username')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('username'));?></div>
				</div>

				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('email')); ?></div>
					<div class="col-sm-10"><?php echo $this->formInput($form->get('email')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('email')); ?></div>
				</div>

				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('name')); ?></div>
					<div class="col-sm-10"><?php echo $this->formInput($form->get('name')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('name')); ?></div>
				</div>

				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('surname')); ?></div>
					<div class="col-sm-10"><?php echo $this->formInput($form->get('surname')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('surname')); ?></div>
				</div>

				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('country')); ?></div>
					<div class="col-sm-6"><?php echo $this->formSelect($form->get('country')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('country')); ?></div>
				</div>

				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('language')); ?></div>
					<div class="col-sm-6"><?php echo $this->formSelect($form->get('language')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('language')); ?></div>
				</div>


				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('password')); ?></div>
					<div class="col-sm-10"><?php echo $this->formInput($form->get('password')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('password')); ?></div>
				</div>

				<div class="form-group">
					<div class="col-sm-2"><?php echo $this->formLabel($form->get('password2')); ?></div>
					<div class="col-sm-10"><?php echo $this->formInput($form->get('password2')); ?></div>
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formElementErrors($form->get('password2')); ?></div>
				</div>

				<div class="form-group">
					<div class="col-sm-10 col-sm-offset-2"><?php echo $this->formRow($form->get('submit')); ?></div>
				</div>
			</div>
			<?php echo $this->form()->closeTag();?>
        </div>
    </div>
</div>


