<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
	<meta charset="utf-8" />
	<title>Authentication Layout: Login</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<meta content="" name="description" />
	<meta content="" name="author" />
    <?php 
    	$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'));
        $this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/plugins/pace/pace-theme-flash.css');
        $this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/plugins/bootstrapv3/css/bootstrap.min.css');                    
		$this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/plugins/bootstrapv3/css/bootstrap-theme.min.css');
		$this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/plugins/font-awesome/css/font-awesome.css');
		$this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/css/animate.min.css');
		$this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/css/style.css');
		$this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/css/responsive.css');
		$this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/css/magic_space.css');
		$this->headLink()->appendStylesheet($this->basePath() . '/themes/webarch/css/custom-icon-set.css');

		echo $this->headLink();

    ?>


	<!-- BEGIN CORE CSS FRAMEWORK -->
	<link href="assets/plugins/pace/pace-theme-flash.css" rel="stylesheet" type="text/css" media="screen"/>
	<link href="assets/plugins/boostrapv3/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="assets/plugins/boostrapv3/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css"/>
	<link href="assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css"/>
	<link href="assets/css/animate.min.css" rel="stylesheet" type="text/css"/>
	<!-- END CORE CSS FRAMEWORK -->

	<!-- BEGIN CSS TEMPLATE -->
	<link href="assets/css/style.css" rel="stylesheet" type="text/css"/>
	<link href="assets/css/responsive.css" rel="stylesheet" type="text/css"/>
	<link href="assets/css/magic_space.css" rel="stylesheet" type="text/css"/>
	<link href="assets/css/custom-icon-set.css" rel="stylesheet" type="text/css"/>
	<!-- END CSS TEMPLATE -->

	<style type="text/css" media="screen">
		.form-control:-moz-placeholder {
		    color: #C8C8C8;
		}		
		:-moz-placeholder {
		    color: #C8C8C8 !important;
		}
		.form-error { list-style: none; margin: 0; padding: 0; font-size: 11px; }

	</style>
</head>
<!-- END HEAD -->

<!-- BEGIN BODY -->
<body class="error-body no-top lazy"  data-original="assets/img/work.jpg"  style="background-image: url('assets/img/work.jpg')"> 

	<div class="container">
		<?php echo $this->content; ?>
	</div>
	<!-- END CONTAINER -->

	<!-- BEGIN CORE JS FRAMEWORK-->
	<script src="assets/plugins/jquery-1.8.3.min.js" type="text/javascript"></script>
	<script src="assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="assets/plugins/pace/pace.min.js" type="text/javascript"></script>
	<script src="assets/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
	<script src="assets/plugins/jquery-lazyload/jquery.lazyload.min.js" type="text/javascript"></script>
	<script src="assets/js/login_v2.js" type="text/javascript"></script>
	<!-- BEGIN CORE TEMPLATE JS -->

<!-- END CORE TEMPLATE JS -->
</body>



</html>

