<h1>Login</h1>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <div class="col-sm-6"><?php echo $this->formInput($form->get('email')); ?></div>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <div class="col-sm-6"><?php echo $this->formInput($form->get('password')); ?></div>
        </div>

        <div class="form-group">
            <div class="col-md-6 col-md-offset-2"><?php echo $this->formRow($form->get('submit')); ?></div>
        </div>

<?php echo $this->form()->closeTag();?>