<style>
	.combodate .select2 { display: inline-block; float: left; margin-right: 15px; }


</style>
<div class="row">
	<div class="col-lg-12">
		<div class="grid simple">
			<div class="grid-title no-border">
				<h4>Create new <span class="semi-bold">Campaign</span></h4>
			</div>

			<div class="grid-body no-border">
				<div class="row">
					<div class="col-md-6">
						<h3>Campaign <span class="semi-bold">Details</span></h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
						<br>
						<div class="clearfix"></div>

							<?php
							$form = $this->form;
							$form->prepare();
							echo $this->form()->openTag($form);
							?>

					        <div class="form-group">
					            <?php echo $this->formLabel($form->get('name')); ?>
					            <span class="help">e.g. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span>
					            <div class="controls"><?php echo $this->formInput($form->get('name')); ?></div>
					            <?php echo $this->formElementErrors()
					            			->setMessageOpenFormat('<div class="help-inline text-danger">')
					            			->setMessageSeparatorString('</div><div class="help-inline">')
					            			->setMessageCloseString('</div>')->render($form->get('name'));
					            			// http://stackoverflow.com/questions/13765662/add-class-attribute-to-form-errors
					            			?>
					        </div>

					        <div class="form-group">
					            <?php echo $this->formLabel($form->get('started_at')); ?>
					            <span class="help">e.g. Excepteur sint occaecat cupidatat non proident.</span>
					            <div class="clearfix"></div>
					            <?php echo $this->formInput($form->get('started_at')); ?>
					            
					        </div>

					        <div class="form-group">
					            <?php echo $this->formLabel($form->get('ended_at')); ?>
					            <span class="help">e.g. Duis aute irure dolor in reprehenderit in voluptate velit.</span>
					            <div class="clearfix"></div>
					            <?php echo $this->formInput($form->get('ended_at')); ?>
					        </div>


					        <div class="form-group">
					        	<?php echo $this->formLabel($form->get('bar')); ?>
					        	<span class="help">e.g. Lorem ipsum dolor sit amet, consectetur.</span>
					        	<div class="controls"><?php echo $this->formInput($form->get('bar')); ?></div>
					        	<?php echo $this->formElementErrors($form->get('bar')); ?>
					        </div>


					        <div class="form-group">
					        	<?php echo $this->formLabel($form->get('foo')); ?>
					        	<span class="help">e.g. Lorem ipsum dolor sit amet, consectetur.</span>
					        	<div class="controls"><?php echo $this->formInput($form->get('foo')); ?></div>
					        	<?php echo $this->formElementErrors($form->get('foo')); ?>
					        </div>


					        <div class="form-group">
					        	<label class="form-label" for="name">Operator</label>
					        	<span class="help">e.g. Lorem ipsum dolor sit amet, consectetur.</span>
					        	<div class="controls">
						        	<select name="" class="select2" style="width:100%">
						        		<option value="">Operator</option>
						        	</select>
					        	</div>
					        </div>

					        <div class="form-group">
					        	<label class="form-label" for="name">Category</label>
					        	<div class="controls">
						        	<select name="" class="select2" style="width:100%">
						        		<option value="">Category</option>
						        	</select>
						        </div>
					        </div>

					        <div class="form-group">
					        	<label class="form-label" for="name">Language(s)</label>
					        	<select name="" class="select2" style="width:100%">
					        		<option value="">Language</option>
					        		<option value="">English</option>
					        		<option value="">French</option>
					        	</select>
					        </div>


					        <div class="form-group">
					        	<label class="control-label" for="name">Description</label>
					        	<textarea class="form-control" rows="4"></textarea>
					        </div>


					        <div class="form-group">
					            <div class=""><?php echo $this->formRow($form->get('submit')); ?></div>
					        </div>

							<?php echo $this->form()->closeTag();?>
					</div>

					<!-- begin right col -->
					<div class="col-md-6">
						<h3>Campaign <span class="semi-bold">Options</span></h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
						<br>
						<div class="row-fluid">
					        <div class="form-group">
								<div class="checkbox check-default">
									<input value="1" id="checkbox1" type="checkbox" checked="checked">
									<label for="checkbox1">Controll URL</label>
								</div>
								<div class="checkbox check-default">
									<input value="1" id="checkbox2" type="checkbox">
									<label for="checkbox2">Another Campaign option</label>
								</div>
							</div>
						</div>

						<hr>

					</div>
					<!-- eof righ col -->

				</div>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col-lg-12">
		<?php if(!empty($this->campaign)) var_dump($this->campaign); ?>
	</div>
</div>


<script>
$(document).ready(function() {



	// http://vitalets.github.io/combodate/#docs
    $(function(){
    	// $('.datetime').combodate();

    	$('#started_at').combodate({
			minYear: 2010,
			maxYear: 2015,
			minuteStep: 10,
			smartDays: true,
			customClass: "select2"
		});

    	$('#ended_at').combodate({
			minYear: 2010,
			maxYear: 2020,
			minuteStep: 10,
			smartDays: true,
			customClass: "select2"
		});

    });

	$("form").submit(function( event ) {
		//alert( $("#started_at").val() );
		//event.preventDefault();
	});


	$(function(){
		$(".select2").select2({
			//width: 'resolve',
			minimumResultsForSearch: -1,
			dropdownAutoWidth : true
		});
	});

});
</script>