<div class="row">
	<div class="col-lg-12">
		<div class="grid simple">
			<div class="grid-title no-border">
				<h4>Campaign <span class="semi-bold">Results</span></h4>
				<div class="tools">
					<a class="collapse" href="javascript:;"></a>
					<a class="config" data-toggle="modal" href="#grid-config"></a>
					<a class="reload" href="javascript:;"></a>
					<a class="remove" href="javascript:;"></a>
				</div>
			</div>

			<div class="grid-body no-border">
				<h3>Campaign <span class="semi-bold">Results</span></h3>

				<table class="table table-hover table-striped">
				    <thead>
				        <tr>
				            <th>
					            <div class="checkbox check-default">
					            	<input id="checkbox0" type="checkbox" class="checkall">
					            	<label for="checkbox0"></label>
					            </div>
				            </th>
				            <th>ID</th>

				            <th><?php echo $this->translate('Name');?></th>
				            <th><?php echo $this->translate('Operator');?></th>
				            <th><?php echo $this->translate('Validated');?></th>
				            <th><?php echo $this->translate('Onhold');?></th>
				            <th><?php echo $this->translate('Created');?></th>
				            <th><?php echo $this->translate('Status');?></th>
				            <th><?php echo $this->translate('Actions');?></th>
				        </tr>
				    </thead>
				    <tbody>
				    <?php if(!empty($paginator)): foreach ($paginator as $campaign) : ?>
					    <?php $id = $campaign->getId(); ?>
					    <?php $checkbox = "checkbox{$id}"; ?>
				    	<tr>
				    		<td>
					    		<div class="checkbox check-default">
					    			<input value="1" id="<?=$checkbox;?>" type="checkbox">
					    			<label for="<?=$checkbox;?>"></label>
					    		</div>
				    		</td>
				    		<td><?php echo $campaign->getId(); ?></td>
				    		<td><?php echo $campaign->getName(); ?></td>
				    		<td><?php echo $campaign->getOperator()->getName(); ?></td>
				    		<td><b class="text-success"><?= number_format(rand(2235, 10987),2)?> &euro;</b></td>
				    		<td><b class="muted"><?= number_format(rand(2235, 10987),2)?> &euro;</b></td>
				    		<td><?php echo $campaign->getCreatedAt(); ?></td>
				    		<td><?php #echo $campaign->getStatus(); ?></td>
				    		<td>
					    		<div class="btn-group pull-right">
					    			<button class="btn btn-mini btn-white">Action</button>
					    			<button class="btn btn-mini btn-white dropdown-toggle" data-toggle="dropdown">
										<span class="caret"></span>
									</button>
									<ul class="dropdown-menu">
										<li><a href="<?php echo $this->url('backoffice/campaign', 
										array('action'=>'edit', 'id' => $campaign->getId()));?>">Edit</a></li>
										<li><a href="#">View</a></li>
										<li><a href="#">Delete</a></li>
									</ul>
					    		</div>
				    		</td>
				    	</tr>
				    <?php endforeach; endif; ?>
				    </tbody>
				</table>

				<div>
				<?php 
				// see https://github.com/tahmina8765/zf2_search_with_pagination_example
				// http://zf2.readthedocs.org/en/latest/tutorials/tutorial.pagination.html
				echo $this->paginationControl(
					// the paginator object
					$this->paginator, 
					// the scrolling style
					'sliding',
					// the partial to use to render the control
				    array('partial/paginator.phtml', 'Backoffice'), 

				    // the route to link to when a user clicks a control link
				    array('route' => 'backoffice/campaign')

				    ); 
				?>	
				</div>

			</div>
		</div>
	</div>
</div>