<?php
// module/Backoffice/view/backoffice/user/delete.phtml:

$title = 'Delete user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete '<?php echo $this->escapeHtml($user->getUsername() ); ?>'</p>

<?php $url = $this->url('backoffice/user', array('action' => 'delete', 'id' => $this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
	<div>
	    <input type="hidden" name="id" value="<?php echo (int) $user->getId(); ?>" />
	    <input type="submit" class="btn btn-success btn-cons" name="del" value="Yes" />
	    <input type="submit" class="btn btn-danger btn-cons" name="del" value="No" />
	</div>
</form>