<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <!-- Assetic Styles and Scripts -->
        <?php
            echo $this->plugin('HeadLink');
            echo $this->plugin('HeadStyle');
            echo $this->plugin('HeadScript');
        ?>
        <link href="/assets/base_css.css" media="screen" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="/assets/base_js.js"></script>

    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('backoffice') ?>">
                        <img src="<?php echo $this->basePath('') ?>" alt="" />&nbsp;<?php echo $this->translate('Backoffice') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('backoffice') ?>"><?php echo $this->translate('Dashboard') ?></a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown">Users <b class="caret"></b></a> 
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('backoffice/manager'); ?>">Managers</a></li>
                                <li><a href="<?php echo $this->url('backoffice/affiliate'); ?>">Affiliates</a></li>
                            </ul>
                            
                        </li>
                        <li><a href="<?php echo $this->url('backoffice/site') ?>"><?php echo $this->translate('Sites') ?></a></li>
                        <li><a href="<?php echo $this->url('backoffice') ?>"><?php echo $this->translate('Campaigns') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <!-- container -->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
        </div> 
        <!-- /container -->
        
    </body>

</html>