<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Assetic Styles and Scripts -->
        <?php
            #echo $this->headScript()->appendFile($this->basePath() . '/Application/js/jquery.min.js', 'text/javascript');
            echo $this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js', 'text/javascript');
            echo $this->headScript()->appendFile($this->basePath() . '/js/bootstrap.js', 'text/javascript');
            echo $this->headScript()->appendFile($this->basePath() . '/js/application.js', 'text/javascript');
            echo $this->headScript()->appendFile($this->basePath() . '/js/modern-business.js', 'text/javascript');

            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.css');
            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css');
            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/modern-business.css');
            echo $this->headLink()->appendStylesheet($this->basePath() . '/css/font-awesome.min.css');
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                    <img src="<?php echo $this->basePath('assets/images/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;
                    <?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="<?php echo $this->url('signup') ?>"><?php echo $this->translate('Signup') ?></a></li>
                        <li><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>


        
        <?php echo $this->content; ?>




        <div class="section-colored text-center" style="background:#1B1E24;">
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                    </div>
                </div>
            </footer>
        </div> <!-- /container -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
