<h1>Affiliates</h1>
<div class="row">
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('username')); ?>
            <?php echo $this->formInput($form->get('username')); ?>
        </div>


        <?php echo $this->formRow($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag();?>

<div class="row">
	<div class="col-lg-12">
		<table class="table table-hover table-striped">
		    <thead>
		        <tr>
		            <th><input type="checkbox"></th>
		            <th>ID</th>
		            <th>Username</th>
		            <th>FirstName</th>
		            <th>Created</th>
		            <th>Status</th>
		            <th>Actions</th>
		        </tr>
		    </thead>
		    <tbody>
		    <?php if(!empty($paginator)): foreach ($paginator as $affiliate) : ?>
		    	<tr>
		    		<td><input type="checkbox"></td>
		    		<td><?php echo $affiliate->getId(); ?></td>
		    		<td><?php echo $affiliate->getUsername(); ?></td>
		    		<td><?php echo $affiliate->getFirstName(); ?></td>
		    		<td><?php echo $affiliate->getCreatedAt(); ?></td>
		    		<td><?php echo $affiliate->getStatusName(); ?></td>
		    		<td>Edit | View</td>
		    	</tr>
		    <?php endforeach; endif; ?>
		    </tbody>
		</table>
	</div>
</div>

<div>
<?php // add at the end of the file after the table
echo $this->paginationControl(
    $this->paginator,
    'sliding',
    array('partial/paginator.phtml', 'Backoffice'),
    array('route' => 'backoffice/affiliate')
); 
?>	
</div>