<h1>Affiliates</h1>

<div class="row">
	<?php
		$form = $this->form;
		$form->prepare();
		echo $this->renderForm($form);

	?>	
</div>

<?php /*
<hr>
<div class="row">
	<?php
		$form = $this->form;
		$form->prepare();
		echo $this->form()->openTag($form);
	?>

    <div class="form-group">
        <?php echo $this->formLabel($form->get('username')); ?>
        <?php echo $this->formInput($form->get('username')); ?>
    </div>

    <?php echo $this->formRow($form->get('submit')); ?>
    <?php echo $this->form()->closeTag();?>
</div>
<hr>
*/ ?>

<div class="row">
	<div class="col-lg-12">
		<div class="grid simple">
			<div class="grid-body">
				<h3>Affiliate <span class="semi-bold">Results</span></h3>
				<table class="table table-hover table-striped">
				    <thead>
				        <tr>
				            <th>
					            <div class="checkbox check-default">
					            	<input id="checkbox0" type="checkbox" class="checkall">
					            	<label for="checkbox0"></label>
					            </div>
				            </th>
				            <th>ID</th>
				            <th><?php echo $this->translate('Username');?></th>
				            <th><?php echo $this->translate('Name');?></th>
				            <th><?php echo $this->translate('Surname');?></th>
				            <th><?php echo $this->translate('Validated');?></th>
				            <th><?php echo $this->translate('Created');?></th>
				            <th><?php echo $this->translate('Status');?></th>
				            <th><?php echo $this->translate('Actions');?></th>
				        </tr>
				    </thead>
				    <tbody>
				    <?php if(!empty($paginator)): foreach ($paginator as $affiliate) : ?>
					    <?php $id = $affiliate->getId(); ?>
					    <?php $checkbox = "checkbox{$id}"; ?>
				    	<tr>
				    		<td>
					    		<div class="checkbox check-default">
					    			<input value="1" id="<?=$checkbox;?>" type="checkbox">
					    			<label for="<?=$checkbox;?>"></label>
					    		</div>
				    		</td>
				    		<td><?php echo $affiliate->getId(); ?></td>
				    		<td><a href="#"><?php echo $affiliate->getUsername(); ?></a></td>
				    		<td><?php echo $affiliate->getName(); ?></td>
				    		<td><?php echo $affiliate->getSurname(); ?></td>
				    		<td><b class="text-success"><?= number_format(rand(2235, 10987),2)?> &euro;</b></td>
				    		<td><?php echo $affiliate->getCreatedAt(); ?></td>
				    		<td><?php echo $affiliate->getStatusName(); ?></td>
				    		<td>Edit | View</td>
				    	</tr>
				    <?php endforeach; endif; ?>
				    </tbody>
				</table>

				<div>
				<?php echo $this->paginationControl($this->paginator, 'sliding',
				    array('partial/paginator.phtml', 'Backoffice'), array('route' => 'backoffice/affiliate')); ?>	
				</div>

			</div>
		</div>
	</div>
</div>

