<div class="row">
	<div class="col-lg-12">
		<div class="grid simple">
			<div class="grid-body no-border" style="padding:15px;">
				<h4>Advanced <span class="semi-bold">Search</span></h4>
				<div class="row form-row">
					<div class="col-md-3">
						<select id="" class="select2 form-control" name="">
							<option value="1">Male</option>
							<option value="2">Female</option>
						</select>
					</div>
					<div class="col-md-3">
						<input id="" class="form-control" type="text" placeholder="Field1" name="">
					</div>
					<div class="col-md-3">
						<input id="" class="form-control" type="text" placeholder="Field2" name="">
					</div>
					<div class="col-md-3">
						<input id="" class="form-control" type="text" placeholder="Field3" name="">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="grid simple">

			<div class="grid-title">
				<h4>Search <span class="semi-bold">Results</span></h4>
				<div class="tools">
					<a class="collapse" href="javascript:;"></a>
					<a class="config" data-toggle="modal" href="#grid-config"></a>
					<a class="reload" href="javascript:;"></a>
					<a class="remove" href="javascript:;"></a>
				</div>
			</div>

			<div class="grid-body">
				<div class="row">
					<h3>Search <span class="semi-bold">Results</span></h3>
					<p>Basic buttons are traditional buttons with borders and background. Use any of the available button classes to quickly create a styled button. <br>Compatible for bootstrap version 2 and 3.</p>

					<table class="table table-striped table-flip-scroll cf">
					    <thead>
					        <tr>
					            <th>
					            	<div class="checkbox check-default">
					            		<input id="checkbox0" type="checkbox" class="checkall">
					            		<label for="checkbox0"></label>
					            	</div>
					            </th>
					            <th>ID</th>
					            <th>URL</th>
					            <th>Validated</th>
					            <th>Onhold</th>
					            <th>Created</th>
					            <th>Actions</th>
					        </tr>
					    </thead>
					    <tbody>
					    <?php if(!empty($paginator)): foreach ($paginator as $site) : ?>
					    	<?php $id = $site->getId(); ?>
					    	<?php $checkbox = "checkbox{$id}"; ?>
					    	<tr>
					    		<td>
					    			<div class="checkbox check-default">
					    				<input value="1" id="<?=$checkbox;?>" type="checkbox">
					    				<label for="<?=$checkbox;?>"></label>
					    			</div>
					    		</td>
					    		<td><?php echo $site->getId(); ?></td>
					    		<td><span class="label"><?=rand(0,9)?></span> <?php echo $site->getUrl(); ?> </td>
					    		<td><b class="text-success"><?= number_format(rand(2235, 10987),2)?> &euro;</b></td>
					    		<td><b class="muted"><?= number_format(rand(678, 1234),2)?> &euro;</b></td>
					    		<td><?php echo $site->getCreatedAt(); ?></td>
					    		<td>
					    			<div class="btn-group pull-right">
					    				<button class="btn btn-mini btn-white">Action</button>
					    				<button class="btn btn-mini btn-white dropdown-toggle" data-toggle="dropdown">
											<span class="caret"></span>
										</button>
										<ul class="dropdown-menu">
											<li><a href="#">Edit</a></li>
											<li><a href="#">View</a></li>
											<li><a href="#">Delete</a></li>
										</ul>
					    			</div>
					    		</td>
					    	</tr>
					    <?php endforeach; endif; ?>
					    </tbody>
					</table>
				</div>

				<div>
					<?php // add at the end of the file after the table
					echo $this->paginationControl(
					    $this->paginator,
					    'sliding',
					    array('partial/paginator.phtml', 'Backoffice'),
					    array('route' => 'backoffice/site')
					); 
					?>	
				</div>

			</div>
		</div>
	</div>
</div>

<script>
	$( document ).ready(function() {
		$(".select2").select2();
	});
</script>