<h1>Sites</h1>
<div class="row">
	<div class="col-lg-12">
		<table class="table table-hover table-striped">
		    <thead>
		        <tr>
		            <th><input type="checkbox"></th>
		            <th>ID</th>
		            <th>URL</th>
		            <th>Created</th>
		            <th>Actions</th>
		        </tr>
		    </thead>
		    <tbody>
		    <?php if(!empty($paginator)): foreach ($paginator as $site) : ?>
		    	<tr>
		    		<td><input type="checkbox"></td>
		    		<td><?php echo $site->getId(); ?></td>
		    		<td><?php echo $site->getUrl(); ?></td>
		    		<td><?php echo $site->getCreatedAt(); ?></td>
		    		<td>Edit | View</td>
		    	</tr>
		    <?php endforeach; endif; ?>
		    </tbody>
		</table>
	</div>
</div>

<div>
<?php // add at the end of the file after the table
echo $this->paginationControl(
    $this->paginator,
    'sliding',
    array('partial/paginator.phtml', 'Backoffice'),
    array('route' => 'backoffice/site')
); 
?>	
</div>